version: "3.8"

services:

  hub-agent:
    pull_policy: always  
    image: ghcr.io/traefik/hub-agent-traefik:v1.1.0
    container_name: hub-agent
    restart: on-failure
    env_file:
      - .env
    command:
      - run
      - --hub.token=${hub.token}
      - --auth-server.advertise-url=http://hub-agent
      - --traefik.host=traefik
      - --traefik.tls.insecure=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-hub
    depends_on:
      - traefik

  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      - --experimental.hub=true
      - --hub.tls.insecure=true
      - --metrics.prometheus.addrouterslabels=true
    networks:
      - traefik-hub

networks:
  traefik-hub: {}
